#!/usr/bin/env python3
# -*- coding: utf-8 -*-
##########################################################################
# hostp2pd - The Wi-Fi Direct Session Manager
# wpa_cli controller of Wi-Fi Direct connections handled by wpa_supplicant
# https://github.com/Ircama/hostp2pd
# (C) Ircama 2021 - CC-BY-NC-SA-4.0
#########################################################################

name: Upload hostp2pd Package to PyPI and TestPyPI

#on:
#  release:
#    types: [created]

#on: [push]

on:
   push:
     tags:
       - 'v*'

env:
  resourceId: ${{ github.run_number }}

jobs:
  build-n-publish:
    name: Build and publish Python to PyPI and TestPyPI
    runs-on: ubuntu-latest

    # Checking out the project and building distributions
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # This will download your repository into the CI runner and then install and activate Python

    - name: Install upgrade pip
      run: >-
        python -m
        pip install
        --upgrade pip
    - name: Install dependencies
      run: >-
        python -m
        pip install pyyaml python-daemon
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    # This will create the /dist directory including the package build.

    - name: Publish hostp2pd to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish hostp2pd to PyPI
      #if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
    # This will publish the /dist directory.
