#!/usr/bin/env python3
# -*- coding: utf-8 -*-
##########################################################################
# hostp2pd - The Wi-Fi Direct Session Manager
# wpa_cli controller of Wi-Fi Direct connections handled by wpa_supplicant
# https://github.com/Ircama/hostp2pd
# (C) Ircama 2021 - CC-BY-NC-SA-4.0
#########################################################################

name: Upload hostp2pd Package to PyPI and TestPyPI

#on:
#  release:
#    types: [created]

#on: [push]

on:
   push:
     tags:
       - 'v*'

env:
  resourceId: ${{ github.run_number }}

jobs:
  build-n-publish:
    name: Build and publish Python to PyPI and TestPyPI
    runs-on: ubuntu-latest

    # Checking out the project and building distributions
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # This will download your repository into the CI runner and then install and activate Python

    - name: Install upgrade pip
      run: >-
        python -m
        pip install
        --upgrade pip
    - name: Install dependencies
      run: >-
        python -m
        pip install pyyaml python-daemon setuptools wheel twine
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    # This will create the /dist directory including the package build.

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload  --repository pypi dist/*
        twine upload  --repository testpypi dist/*
    # This will publish the /dist directory.
